AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
    TwilioLayer:
      Type: AWS::Serverless::LayerVersion
      Properties:
        LayerName: twilio-dependencies
        Description: Dependencies for twilio
        ContentUri: dependencies/
        CompatibleRuntimes:
          - python3.9
        RetentionPolicy: Retain
    VoicedFunction:
        Type: AWS::Serverless::Function 
        Properties:
            CodeUri: voice/src/
            Handler: app.lambda_handler
            Runtime: python3.9
            Environment:
              Variables:
                twiml_table: !Ref TwimlTable
                blocked_table: !Ref BlockedTable
            Layers:
              - !Ref TwilioLayer
            Policies:
              - CloudWatchPutMetricPolicy: {}
              - Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - 'dynamodb:BatchGetItem'
                      - 'dynamodb:ConditionCheckItem'
                      - 'dynamodb:GetItem'
                      - 'dynamodb:Scan'
                      - 'dynamodb:Query'
                      - 'dynamodb:GetRecords'
                    Resource: 
                      - !GetAtt TwimlTable.Arn
                      - !GetAtt BlockedTable.Arn
            Events:
              WarmingSchedule:
                Type: Schedule
                Properties:
                  Schedule: rate(5 minutes)
                  Input: '{ "warmer":true }'
              TwilioAPI:
                  Type: Api 
                  Properties:
                      Path: /voice
                      Method: post
    TwimlTable:
      Type: AWS::DynamoDB::Table
      Properties:  
        AttributeDefinitions:
          - 
            AttributeName: "did"
            AttributeType: "S"
          - 
            AttributeName: "step"
            AttributeType: "S"
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - 
            AttributeName: "did"
            KeyType: "HASH"
          - 
            AttributeName: "step"
            KeyType: "RANGE"
    BlockedTable:
      Type: AWS::DynamoDB::Table
      Properties:  
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - 
            AttributeName: "did"
            AttributeType: "S"
        KeySchema:
          - 
            AttributeName: "did"
            KeyType: "HASH"
          
